---
title: The Liberal Arts
---

The liberal arts:

* The Trivium: The three arts of language (pertaining to mind)
  1. logic: the art of thinking
  2. grammar: the art of inventing symbols and combining them to express thought
  3. rhetoric: the art of effective communication of though from mind to another, 
     the adaptation of language to circumstance.
* The Quadrivium: the four arts of quantity (pertaining to matter)
  1. Arithmetic: the theory of number, or study of patterns and symmetry per se.
  2. Music: the theory of number as it behaves in time (dynamically), or study of dynamic patterns and symmetry.
  3. Geometry: the theory of number in space, or the study of patterns and symmmetry of space
  4. Astronomy: the theory of number in space and time, or the study of patterns and symmetry of space and time, i.e.
     the combination of music and geometry. (Therefore sometimes referred to as the Music of the spheres.)

Bachelor of **Arts** is awarded to those who complete their studies in the seven liberal **arts**, the trivium forming the basis.
Master of **Arts** is awarded to those who demonstrate greater more proficiency in these seven liberal arts.


## Why *Liberal*? 

Liberal arts differ from:

* utilitarian arts: salesmanship, printing, editing, banking, law, medicine, carpentry, plumbing, ...
* the seven *fine* arts: 
  1. architecture
  2. *instrumental* music (different from the liberal art music)
  3. sculpture
  4. painting
  5. literature (of popular / entertainment type)
  6. drama
  7. dance
  
**Main difference**: both utilitarian and fine arts are *transitive* activities. They produce a product 
that is consumed by the consumer. Their products have a commercial value. Therefore the artist is usually payed
for his work. 
The artist produces a product
that begins in the artist / agent, it goes out from him and ends in the object produced (or the consumer that 
consumes the object). 

But in liberal arts the action begins in the agent and ends in the agent, who is perfected and transformed
by exercising the art. It does not have a direct commercial or transactional value and the artist is not payed 
for his work. (Just like in the University students are not payed for their work, but on the contrary usually 
pay the instructors or the University).

Analogy: transitive and intransitive verbs:

1. The stenographer types the letters: "types" is a transitive verb. The action begins by the stenographer
   but ends in the letters being typed.
2. The rose blooms: "bloom" is an intransitive verb - the action begins in the rose and ends in the rose.
   The rose itself is transformed by the action of blooming. 

Analogy: the active vs contemplative christian life: the primary purpose of both is the glory of God, but
they differ in means and in secondary purpose.

1. active Christian life: its purpose is transitive - to do good to others by
   * preaching the word of God
   * teaching
   * relieving teh distress of the sick and needy
   * ...
2. contemplative Christian life: its purpose is intransitive - to perfect the agent, the soul that contemplates.
   Perfecting of the soul by increasing its participation in the life of God, who dwells in it by grace, is in
   itself the higher work. Therefore contemplation is in itself superior to action.

Classes of goods:

1. Valuable goods: They increase the intrinsic worth of their possessor, such as knowledge, virtue, health, etc
2. Useful goods: They enable one to acquire valuable goods, and are desired as means 
   such as food, medicine, money, tools, books, etc
3. Pleasurable goods: Desired for their own sake due to the satisfaction they give although do not add to the 
   intrinsic value / worth of the possessor, such as happiness, an honorable reputation, social prestige,
   a gorgeous sunset, flowers, tasty food, ice cream, etc. 

Often goods belong to various classes simultaneously; many tasty food are healthy and therefore useful. Knowledge
is a valuable good, but often it is pleasurable as well, as it is fun to learn new and stimulating subjects.

Utilitarian / servile arts enable a man to be a servant - of another man, of the state, of a corporation, or even
his own business enterprise - and to earn living. The liberal arts, teach one how to live by training his faculties
and bringing them to perfection, thus enabling one to rise above his material environment and live an intellectual,
a rational, and therefore a free life in gaining truth. 

Each liberal art is both an art (how to do something / technique) and science (body of knowledge). 
An art can be successfully applied without a knowledge of formal laws the art. But knowledge thereof 
increases effectiveness and confidence in applying the art. 

Trivium is the fundamental instrument at all levels of education, because the arts of logic, grammar, and rhetoric
are the arts of communication itself and since communication involves the simultaneous exercise of logic,
grammar, and rhetoric. 

In education the arts of logic, grammar and rhetoric are practiced simultaneously by the teacher and the pupil, 
the speaker and the listener, or the writer and the reader.

reading, writing, speaking, and listening are means of communication. Communication, as the etymology suggests 
is something shared by two parties and takes place only when to minds meet. 

* if the reader / listener receives in his mind the same **ideas** and **emotions** that the writer / speaker 
  wished to convey, he understands (although may disagree)
* if he receives no idea or emotion he does not understand.
* if he receives different ideas and emotions, not intended, he misunderstands. 


By the way, notice the analogy:
reading / listening ~ writing / speaking. Reading and listening, even though seemingly passive, involve acting thinking and 
application of logic, since we constantly agree or disagree with what we read or hear. 

The trivium is used vitally in composition (writing), but also in in literature (reading). 

Education is the highest of arts because it imposes forms (ideas and ideals) not on matter, as do other arts like carpentry
or sculpture, but on mind. 

The three arts of language, logic, grammar, and rhetoric, provide discipline of mind inasmuch as mind finds expression
in language. The four arts of quantity, arithmetic, geometry, music, and astronomy provide means for the study of matter
inasmuch as quantity, or, more precisely, extension, is the oustanding characteristic of nmatter. 

Extension is a characteristic of matter only, whereas number is a characteristic of both matter and spirit. 
Spirits = immaterial beings. 

* knowledge of ourselves $\Rightarrow$ mind
* knowledge of the world $\Rightarrow$ matter
* knowledge of God and other spirits.



